//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseTutor { get; set; }
    }
}
